---
title: "BNPParibasCardif"
author: "Oswaldo F. Domejean"
date: "February 19, 2016"
output: word_document
---

Libraries

```{r}
library(ggplot2)
library(readr)
library(dplyr)
library(caret)
library(ellipse)
library(matrixStats)
library(vcd)
library(sqldf)
```

Data loading

```{r, echo=FALSE}
setwd("~/Dropbox/Kaggle/BNP Paribas Cardif Claims Management")
#setwd("C:/Users/Ing-Figueroa/Dropbox/Kaggle/BNP Paribas Cardif Claims Management")
cat("Set seed\n")
set.seed(0)

cat("Read the train and test data\n")
train <- read_csv("train.csv")
test  <- read_csv("test.csv")
```

Recode NAs to -997

```{r}

train[is.na(train)]   <- -997
test[is.na(test)]   <- -997


```

Get feature names
```{r}
#feature.names <- names(train)[c(3:ncol(train))]
feature.names <- names(train)


highCorrRemovals <- c("v8","v23","v25","v36","v37","v46",
                      "v51","v53","v54","v63","v73","v81",
                      "v82","v89","v92","v95","v105","v107",
                      "v108","v109","v116","v117","v118",
                      "v119","v123","v124","v128")

train <- train[!(names(train) %in% highCorrRemovals)]
test <- test[!(names(test) %in% highCorrRemovals)]
```

Replace categorical variables with integers

```{r}

for (f in feature.names) {
  if (class(train[[f]])=="character") {
    levels <- unique(c(train[[f]], test[[f]]))
    train[[f]] <- as.integer(factor(train[[f]], levels=levels))
    test[[f]]  <- as.integer(factor(test[[f]],  levels=levels))
  }
}

```

