---
title: "GBM"
author: "Oswaldo F. Domejean"
date: "March 14, 2016"
output: word_document
---

---
title: "PruModelV20"
author: "Oswaldo F. Domejean"
date: "January 5, 2016"
output: word_document
---

Libraries

```{r}
library(gbm)
library(caTools)
```

Data loading
```{r}
setwd("~/Documents/Data Mining/Kaggle/BNP Paribas Cardif Claims Management")
train <- read.table("trainV1.csv", header=T, sep=",")
test <- read.table("testV1.csv", header=T, sep=",") 

```

GBM

```{r}
#indice<-1:5000
#train<-train[indice,]
#test<-test[indice,]

k = 5
submission <- read.table("sample_submission.csv", header=TRUE, sep=',')
ensemble <- rep(0, nrow(test))
n = floor(nrow(train)/k)
for(i in 1:k){
  s1=((i-1)*n+1)
  s2=(i*n)
  subset=s1:s2
  cv.train=train[-subset,!(names(train) %in% c("ID"))]
  test.label <- train[subset,(names(train) %in% c("ID"))]
  cv.test=train[subset,!(names(train) %in% c("ID"))]

  GBMModel <- gbm(target ~.,
              data=cv.train,
              n.trees=1500,
              distribution = "bernoulli",
              interaction.depth=10,
              n.minobsinnode=10,
              shrinkage=0.1,
              # cv.folds=3,
              n.cores=2,
              train.fraction=1,
              bag.fraction=0.7,
              verbose=T)  

  PredGBMtest=predict(GBMModel,newdata=test[,!(names(test) %in% c("ID"))],
                        n.trees=1500,type="response")
  ensemble <- ensemble + PredGBMtest
}

submission$PredictedProb <- ensemble/i
write.csv(submission, "predGBMtest.csv", row.names = FALSE)


summary(GBMModel)
gbm.perf(GBMModel)


```
