---
title: "SVM"
author: "Oswaldo F. Domejean"
date: "March 14, 2016"
output: word_document
---

Libraries

```{r}
library(e1071)
library(caret)
library(RCurl)
library(Metrics)
library(caTools)

```

Data loading
```{r}
setwd("~/Documents/Data Mining/Kaggle/BNP Paribas Cardif Claims Management")
train <- read.table("trainV1.csv", header=T, sep=",")
test <- read.table("testV1.csv", header=T, sep=",") 

```

Model svm CV

```{r}
#conjunto<-1:5000
#train=train[conjunto,]

k = 5
resultCV <- data.frame(ID=integer(), pred=numeric()) 
n = floor(nrow(train)/k)
for(i in 1:k){
  s1=((i-1)*n+1)
  s2=(i*n)
  subset=s1:s2
  cv.train=train[-subset,!(names(train) %in% c("ID"))]
  test.label <- train[subset,(names(train) %in% c("ID"))]
  cv.test=train[subset,!(names(train) %in% c("ID"))]
  
  SVMModel = svm(as.factor(target) ~ .,
               data = cv.train,
               kernel="linear",
               C=2,
               class.weights = c("0" = 0.7, "1" = 0.3),
               scale=TRUE,
               probability = TRUE)

  predSVM <- predict(SVMModel, cv.test[,!(names(cv.test) %in% c("target"))],
                     probability = TRUE)
  
  # head(attr(predSVM, "probabilities")) gives the probability of 1 and zero
  
  temp1<-as.data.frame(attr(predSVM, "probabilities"))
  #names(temp1)<-c("uno", "cero")
  prediccion<-as.data.frame(cbind(test.label,temp1[,1]))
  resultCV<-rbind(resultCV,prediccion)
}

# test dataset prediction

test.label1 <- test[,(names(test) %in% c("ID"))]
predSVMtest=predict(SVMModel,newdata=test[,!(names(cv.test) %in% c("target"))],
                 probability = TRUE)
prediccion1 <- as.data.frame(cbind(test.label1,predSVMtest)) 


write.csv(prediccion1, "predSVMtest.csv", row.names = FALSE)

SVMModel$index
summary(SVMModel)

```

